/* AUTOGENERATED FILE, DO NOT MODIFY */
// Hasq Technology Pty Ltd (C) 2013-2016

typedef unsigned long long ulonglong_128;

#ifdef UNUMBER_SIZE
#undef UNUMBER_SIZE
#endif
#define UNUMBER_SIZE 1

#ifdef UBASE_TYPE
#undef UBASE_TYPE
#endif
#define UBASE_TYPE ulonglong_128

#ifdef Unumber
#undef Unumber
#endif
#define Unumber Unum_128

#ifdef Cunumber
#undef Cunumber
#endif
#define Cunumber Cunum_128

#ifdef cinc
#undef cinc
#endif
#define cinc cinc_128

#ifdef cdec
#undef cdec
#endif
#define cdec cdec_128

#ifdef cequal
#undef cequal
#endif
#define cequal cequal_128

#ifdef cbitorder
#undef cbitorder
#endif
#define cbitorder cbitorder_128

#ifdef cadd
#undef cadd
#endif
#define cadd cadd_128

#ifdef cdiv_QnotND
#undef cdiv_QnotND
#endif
#define cdiv_QnotND cdiv_QnotND_128

#ifdef cshr
#undef cshr
#endif
#define cshr cshr_128

#ifdef cshl
#undef cshl
#endif
#define cshl cshl_128

#ifdef csub
#undef csub
#endif
#define csub csub_128

#ifdef cmul
#undef cmul
#endif
#define cmul cmul_128

#ifdef ciszero
#undef ciszero
#endif
#define ciszero ciszero_128

#ifdef cless
#undef cless
#endif
#define cless cless_128

#ifdef ctozero
#undef ctozero
#endif
#define ctozero ctozero_128

#ifdef cnewzero
#undef cnewzero
#endif
#define cnewzero cnewzero_128

#ifdef csetbit1
#undef csetbit1
#endif
#define csetbit1 csetbit1_128

#ifdef cgetbit
#undef cgetbit
#endif
#define cgetbit cgetbit_128

#ifdef cinvert
#undef cinvert
#endif
#define cinvert cinvert_128

#ifdef cisvalid
#undef cisvalid
#endif
#define cisvalid cisvalid_128

#ifdef cpow
#undef cpow
#endif
#define cpow cpow_128

#ifdef cpow2
#undef cpow2
#endif
#define cpow2 cpow2_128

#ifdef cxxx
#undef cxxx
#endif
#define cxxx cxxx_128
