#!/bin/sh
# Hasq Technology Pty Ltd (C) 2013-2016

: > cunum_def_128.h

echo "/* AUTOGENERATED FILE, DO NOT MODIFY */" >> cunum_def_128.h

while read LINE
do
NL=`echo $LINE | sed -e "s/_2048/_128/g"`
NL=`echo $NL | sed -e "s/define UNUMBER_SIZE 32/define UNUMBER_SIZE 1/g"`
echo $NL >> cunum_def_128.h
echo -n "."
done < cunum_def_2048.h

