wget http://tinycorelinux.net/6.x/x86/tcz/apr.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/apr-util.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/autoconf.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/automake.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/bash.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/binutils.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/bison.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/boost.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/boost-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/bzip2-lib.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/cloog.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/compiletc.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/db.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/db-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/diffutils.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/e2fsprogs_base-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/expat2.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/file.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/findutils.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/flex.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gamin.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gawk.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc_base-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc_libs.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc_libs-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/glib2.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/glibc_base-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gmp.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/grep.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/isl.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libffi.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libgcrypt.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libgpg-error.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libproxy.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libssh2.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/linux-3.16.2_api_headers.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/m4.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/make.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mc.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mkisofs-tools.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mpc.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mpfr.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/ncurses.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/neon.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/nginx.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/openssl-1.0.1.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/openssl-1.0.1-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/patch.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/pcre.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/perl5.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/perl_xml_parser.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/pkg-config.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/readline.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/sed.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/slang.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/sqlite3.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/squashfs-tools.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/svn.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/udev-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/udev-lib.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/util-linux_base-dev.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/wget.tcz
wget http://tinycorelinux.net/6.x/x86/tcz/zlib_base-dev.tcz