
all: ma_dag_ cunumber_ ma_skc_ ma_pkc_ ma_eucl_

clean:
	echo clean

ma_dag_:
	cd ma_dag && make PLAT=$(PLAT)

ma_skc_:
	cd ma_skc && make PLAT=$(PLAT)

cunumber_:
	cd cunumber && make PLAT=$(PLAT)

ma_pkc_:
	cd ma_pkc && make PLAT=$(PLAT)

ma_eucl_:
	cd ma_eucl && make PLAT=$(PLAT)

