wget http://tinycorelinux.net/6.x/x86/tcz/apr.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/apr-util.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/autoconf.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/automake.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/bash.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/binutils.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/bison.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/boost.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/boost-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/bzip2-lib.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/cloog.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/compiletc.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/db.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/db-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/diffutils.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/e2fsprogs_base-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/expat2.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/file.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/findutils.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/flex.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gamin.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gawk.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc_base-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc_libs.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gcc_libs-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/glib2.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/glibc_base-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/gmp.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/grep.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/isl.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libffi.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libgcrypt.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libgpg-error.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libproxy.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/libssh2.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/linux-3.16.2_api_headers.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/m4.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/make.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mc.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mkisofs-tools.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mpc.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/mpfr.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/ncurses.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/neon.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/nginx.tcz -P tcz
#wget http://tinycorelinux.net/6.x/x86/tcz/openssl-1.0.1.tcz -P tcz
#wget http://tinycorelinux.net/6.x/x86/tcz/openssl-1.0.1-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/openssl.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/openssl-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/patch.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/pcre.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/perl5.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/perl_xml_parser.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/pkg-config.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/readline.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/sed.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/slang.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/sqlite3.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/squashfs-tools.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/svn.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/udev-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/udev-lib.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/util-linux_base-dev.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/wget.tcz -P tcz
wget http://tinycorelinux.net/6.x/x86/tcz/zlib_base-dev.tcz -P tcz