all:
	@echo "Usage: clean"

clean:
	rm -f db.sec input.sec output.sec output.opn pqkru db.opn input.opn
	rm -rf        ipch
	rm -rf        vc.sdf
	rm -rf        Debug
	rm -rf        Release
	rm -rf        DebugStatic
	rm -rf        vc.suo vc.*.suo
