const HASQD_RESP =
{
    OK : 'OK',
    IDX_NODN : 'IDX_NODN',
    JOB_QUEUED : 'JOB_QUEUED',
    NO_RECS : 'NO_RECS',
    URF_BAD_FORMAT : 'URF_BAD_FORMAT',
    REQ_MSG_HEAD : 'REQ_MSG_HEAD',
    REQ_DN_BAD : 'REQ_DN_BAD',
    REC_INIT_BAD_N : 'REC_INIT_BAD_N',
    REC_INIT_BAD_S : 'REC_INIT_BAD_S',
    REC_INIT_BAD_KGO : 'REC_INIT_BAD_KGO',
    RECORD_MISMATCH : 'RECORD_MISMATCH',
    WRONG_SEQ_NUMBER : 'WRONG_SEQ_NUMBER',
    REQ_HASHTYPE_BAD : 'REQ_HASHTYPE_BAD',
    REQ_BAD_SIGN : 'REQ_BAD_SIGN',
    CE_QUE_OVERFLOW : 'CE_QUE_OVERFLOW',
    BUSY : 'BUSY',
    REQ_JOBID_BAD : 'REQ_JOBID_BAD',
    JOB_NOINFO : 'JOB_NOINFO',
    REQ_PATH_BAD : 'REQ_PATH_BAD',
    REQ_BAD_CRYPT : 'REQ_BAD_CRYPT'
}
